### ISSUE TITLE
Module schemas omitted --discussion

### ISSUE THREAD

**Issue by TRThurman** [expresslang/schema-manifest#1]
@ronaldtse The example does not include modules.  My understanding of the iso-10303-srl repo is that it is a development repo and not a published HTML repo.
At some point, we may wish to add '-dev' to the end of the name to so indicate.
The current STEP developers are familiar with repo end of name convention of 'dev'.

More discussion needed before action.

**Comment by ronaldtse** [comment]
> iso-10303-srl repo is that it is a development repo and not a published HTML repo.

It builds the HTML site as output but the repo is private. I'm not quite sure of the key differences between a "development" repo and a "production" repo?

> At some point, we may wish to add '-dev' to the end of the name to so indicate.

To the schemas? As a name convention to the schemas, or...?

My personal view is that the `-dev` suffix is from a time when version control software didn't work well. Right now it is very easy to version individual schemas.

**Comment by ronaldtse** [comment]
The module examples are useful because the names of the schemas and the filenames are different. I'll add those.

However, I want to make sure that we're on the same page here, that the "schema manifest" we talk about is not only for being used in the SRL/SMRL, but in general for people who use EXPRESS schemas. Thanks!

**Comment by TRThurman** [comment]
ok I got it. the ...srl was just part of the example.....
carry on.

**Comment by ronaldtse** [comment]
I've added an example for modules, where the schema name path doesn't match with file path.
